### PR TITLE
disable selinux

### PR DESCRIPTION
**Pull request by hudecof**
nginx is not able to connect on django port

as tis application install everything system wide I disabled also selinux instead of creating the rule

### CODE REVIEW

**Comment by hudecof** [comment]
less permissive solution would be

```
- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
```

**Comment by matonb** [comment]
Personally I think disabling SELinux without asking the user is really bad form.

**Comment by hudecof** [comment]
@matonb you're right I updaed the patch to allow http connect

**Comment by openbacchus** [comment]
thank you !

**Pull request merged**
